name: amparesysteminformation
version: 1.0.0
summary: Ampare System Information
description: A Simple But Detailed Application To View System Information
confinement: strict
grade: stable
icon: snap/gui/icon.png
apps:
  amparesysteminformation:
    command: env TMPDIR=$XDG_RUNTIME_DIR desktop-launch $SNAP/amparesysteminformation
    plugs:
      - desktop
      - desktop-legacy
      - home
      - x11
      - unity7
      - browser-support
      - network
      - gsettings
      - pulseaudio
      - opengl
parts:
  app:
    plugin: dump
    stage-packages:
      - libasound2
      - libgconf2-4
      - libnotify4
      - libnspr4
      - libnss3
      - libpcre3
      - libpulse0
      - libxss1
      - libxtst6
    source: linux-unpacked
    after:
      - desktop-gtk2
